name: meshcnn
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.6.8
  - cython
  - pytorch=1.2.0
  - numpy
  - matplotlib=3.0.3
  - pip
  - pykdtree=1.3.4
  - pip:
      - git+https://github.com/lanpa/tensorboardX.git
      - pytest==5.1.1
      - trimesh==3.9.35
      - scipy==1.5.4
